
interface IKisAuth {
    length: number;
    access_token: string,
    token_type: string,
    expires_in: number,
    acess_token_token_expired: string,
}

interface ISectionOutput1 {
    bstp_nmix_hgpr: string,
    bstp_nmix_lwpr: string,
    bstp_nmix_prpr: string,
}

interface IKisSection {
    length: number;
    rt_cd: string,
    msg_cd: string,
    msg1: string,
    output1: ISectionOutput1,
    output2: [],

    stck_bsop_date: string,
    mod_yn: string,
    bstp_nmix_prdy_vrss: string,
    prdy_vrss_sign: string,
    bstp_nmix_prdy_ctrt: string,
    prdy_nmix: string,
    acml_vol: string,
    acml_tr_pbmn: string,
    hts_kor_isnm: string,
    bstp_nmix_prpr: string,
    bstp_cls_code: string,
    prdy_vol: string,
    bstp_nmix_oprc: string,
    bstp_nmix_hgpr: string,
    bstp_nmix_lwpr: string,
    futs_prdy_oprc: string,
    futs_prdy_hgpr: string,
    futs_prdy_lwpr: string,
}

interface IKisAskPrice {
rt_cd: string,
msg_cd: string,
msg1: string,
output1: IAskPriceOutput1,
output2: IAskPriceOutput2,
}


interface IAskPriceOutput1{
    aspr_acpt_hour: string,
    askp1: string,
    askp2: string,
    askp3: string,
    askp4: string,
    askp5: string,
    askp6: string,
    askp7: string,
    askp8: string,
    askp9: string,
    askp10: string,
    bidp1: string,
    bidp2: string,
    bidp3: string,
    bidp4: string,
    bidp5: string,
    bidp6: string,
    bidp7: string,
    bidp8: string,
    bidp9: string,
    bidp10: string,
    askp_rsqn1: string,
    askp_rsqn2: string,
    askp_rsqn3: string,
    askp_rsqn4: string,
    askp_rsqn5: string,
    askp_rsqn6: string,
    askp_rsqn7: string,
    askp_rsqn8: string,
    askp_rsqn9: string,
    askp_rsqn10: string,
    bidp_rsqn1:string,
    bidp_rsqn2: string,
    bidp_rsqn3: string,
    bidp_rsqn4: string,
    bidp_rsqn5: string,
    bidp_rsqn6: string,
    bidp_rsqn7: string,
    bidp_rsqn8: string,
    bidp_rsqn9: string,
    bidp_rsqn10: string,
    askp_rsqn_icdc1: string,
    askp_rsqn_icdc2: string,
    askp_rsqn_icdc3: string,
    askp_rsqn_icdc4: string,
    askp_rsqn_icdc5: string,
    askp_rsqn_icdc6: string,
    askp_rsqn_icdc7: string,
    askp_rsqn_icdc8: string,
    askp_rsqn_icdc9: string,
    askp_rsqn_icdc10: string,
    bidp_rsqn_icdc1: string,
    bidp_rsqn_icdc2: string,
    bidp_rsqn_icdc3: string,
    bidp_rsqn_icdc4: string,
    bidp_rsqn_icdc5: string,
    bidp_rsqn_icdc6: string,
    bidp_rsqn_icdc7: string,
    bidp_rsqn_icdc8: string,
    bidp_rsqn_icdc9: string,
    bidp_rsqn_icdc10: string,
    total_askp_rsqn: string,
    total_bidp_rsqn: string,
    total_askp_rsqn_icdc: string,
    total_bidp_rsqn_icdc: string,
    ovtm_total_askp_icdc: string,
    ovtm_total_bidp_icdc: string,
    ovtm_total_askp_rsqn: string,
    ovtm_total_bidp_rsqn: string,
    ntby_aspr_rsqn: string,
    new_mkop_cls_code: string,
}

interface IAskPriceOutput2{
    antc_mkop_cls_code: string,
    stck_prpr: string,
    stck_oprc: string,
    stck_hgpr: string,
    stck_lwpr: string,
    stck_sdpr: string,
    antc_cnpr: string,
    antc_cntg_vrss_sign: string,
    antc_cntg_vrss: string,
    antc_cntg_prdy_ctrt: string,
    antc_vol: string,
    stck_shrn_iscd: string,
    vi_cls_code: string,
}